### ISSUE TITLE
Expertise sur les noms des fichiers générés à partir du libellé des concepts

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#366]
Vérifier la génération du fichier exporté d'un concept par rapport à son libellé. (Le .odt) .

- [ ] Documenter quelque part (dans le guide d'utilisateur). 
- [ ] Vérifier que le comportement est OK. 
- [ ] Vérifier que le comportement est ISO sur tous les exports de fichiers (Concepts, Collections, SIMS)

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek et @flo7894 je viens de vérifier, et nous faisons quelque chose de simple pour le nom des fichiers des concepts : Nous faisons un camelCase (en utilisant que l'espace comme délimiteur). 

C'est à dire que : "Nom du Fichier" sera renommer en "nomDuFichier". 

Cela vous convient ?

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek je viens de vérifier le point deux. Voici mes résultat. 

Pour un SIMS: 

- sans documents : on utilise l'identifiant du SIMS comme nom de fichier
- avec documents : 
   - le zip : le nom du zip c'"est le labelLg1 du sims (avec des espaces)
   - le nom du .odt du sim c'est exactement la même chose que le zip
   - les documents : pour les noms des documents, nous récupérons ce qui se trouve à la fin de l'URI du document. 
   
   
  Pour les Concepts

- Mutiple : prefLabelLg1 du concept en camelCase (sans les espace) avec l'identifiant concaténé
- Unique : prefLabelLg1 du concept en camelCase (sans les espace) avec l'identifiant concaténé

Pour les Collections : 

- Multiples : prefLabelLg1 du concept en camelCase (sans les espace) avec l'identifiant concaténé
- Unique : prefLabelLg1 du concept en camelCase (sans les espace) avec l'identifiant concaténé


Donc je pense qu'il faut just modifier pour les SIMS @Emilia-Vittek

**Comment by EmmanuelDemey** [comment]
@flo7894  qu'en penses tu ?

**Comment by EmmanuelDemey** [comment]
Une petite relance pour @flo7894 ;)

**Comment by flo7894** [comment]
@EmmanuelDemey 

merci pour ton analyse.

le camelCase me paraît bien. 
il me semble qu'il faut aussi qu'on élimine certain caractère
et qu'on donne une règle systématique entre identifiant_nomFichier et nomFichier_identifiant

on prépare une carte pour le prochain sprint

**Comment by EmmanuelDemey** [comment]
@flo7894 ca roule. Je clos donc celle ci.
