### ISSUE TITLE
Supprimer la caractères diacritique sur les noms des fichiers

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#388]

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey J'ai voulu recetter cette carte avec une liste très longue de caractères diacritiques que je reprends en fonction des résultats : 

**1. pour les concepts, exportation :** 
 _- liste 1 :_ *  \ /: ? "<>| ; ! _ ( )  ' [ ] ~# { } ^ @ % § ° . ==> En ce qui concerne le traitement des caractères diacritiques, ils sont supprimés dans le nom du fichier ==> **Ok  pour tous sauf pour § et °**  Mais, ils n'en sont peut-être pas. Petite remarque supplémentaire, le caractère < est bien traité comme un caractère diacritique pour fixer le nom du fichier, en revanche il est mal interprété pour exporter le contenu du fichier. Cela sera probablement une carte à venir.
 _- liste 2 :_ à â ä é è ê ë î ï û ü ù ö ô ÿ ç ==> En ce qui concerne le traitement des caractères diacritiques, ils sont remplacés par la voyelle ou la consonne correspondant sans caractère diacritique dans le nom du fichier ==> **Ok  pour tous**
 _- liste 3 :_ À Â Ä É È Ê Ë Î Ï Û Ü Ù Ö Ô Ý Ç ==> En ce qui concerne le traitement des caractères diacritiques, ils sont remplacés par la voyelle ou la consonne correspondant sans caractère diacritique dans le nom du fichier ==> **Ok  pour tous**

**2. pour les listes de concepts, exportation :** 
J'ai testé l'exportation avec plusieurs concepts dont deux qui avaient des caractères diacritiques ==> **Ok pour toutes les exportations** (.ods, .odt langue 1, .odt langue 2 et fiches des concepts de la sélection).

**3. pour une liste de concepts résultant de la recherche avancée, exportation :** 
J'ai testé l'exportation avec au moins plusieurs concepts qui avaient des caractères diacritiques ==> **Ok pour toutes les exportations** (.ods, .odt langue 1, .odt langue 2 et fiches des concepts de la sélection).

**4. pour une collection de concepts, exportation :** 
J'ai testé l'exportation avec une collection dont le nom comportait des caractères diacritiques et qui avait des concepts avec des caractères diacritiques aussi  : 
 _- exportation en .ods_ ==>les caractères diacritiques **ne sont pas traités dans le nom du fichier** résultant de l'exportation ;
 _- exportation en .odt langue 1_ ==> les caractères diacritiques **ne sont pas traités dans le nom du fichier** résultant de l'exportation ;
 _- exportation en .odt langue 2_ ==> les caractères diacritiques **ne sont pas traités dans le nom du fichier** résultant de l'exportation ;
 _- exportation des fiches des concepts de la sélection_ ==> les caractères diacritiques **ne sont pas traités ni dans le nom du fichier zip** résultant de l'exportation, **ni dans le nom du dossier** qui contient les fiches des concepts résultant de l'exportation. En revanche, le traitement est **Ok pour les fiches des concepts de la sélection** (on retombe sur le point 1).

**5. pour une liste de collections de concepts, exportation :** 
J'ai testé l'exportation avec deux collections dont une qui avait des caractères diacritiques :
_- exportation en .ods_ ==> le traitement est **Ok sur le nom du zip** , mais les caractères diacritiques **ne sont pas traités dans les noms du fichier** résultant de l'exportation pour chaque collection ;
_- exportation en .odt langue 1_ ==> le traitement est **Ok sur le nom du zip** , mais les caractères diacritiques **ne sont pas traités dans les noms du fichier** résultant de l'exportation pour chaque collection ;
 _- exportation en .odt langue 2_ ==> le traitement est **Ok sur le nom du zip**, mais les caractères diacritiques **ne sont pas traités dans les noms du fichier** résultant de l'exportation pour chaque collection ;
_- exportation des fiches des concepts de la sélection_ ==> traitement **Ok sur le nom du fichier zip**. Les caractères diacritiques **ne sont pas traités dans le nom des dossiers** résultant de l'exportation qui contiennent les fiches des concepts à exporter. En revanche, le traitement est **Ok pour les fiches des concepts de la sélection** (on retombe sur le point 1).

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey  en résumé (après ma fausse manip sur GitHub - désolée) : 

- tu m'avais annoncé que c'était développé pour les _concepts_ et les _collections_ ;
- je trouve que : 
            + c'est bien appelé et déroulé (**= OK)** pour les _concepts_, les _listes de concepts_ et les _résultats des recherches avancées de concepts_ ;
            + cela pose **problème** pour les _collections_ et les _listes de collections_, où cela ne s'applique qu'à l'exportation des fiches des concepts sélectionnés et pas aux dossiers et fichiers zip qui regroupent le tout.

Merci pour tout ce qui est déjà fait. N'hésite pas à me solliciter pour le reste si besoin, étant entendu que nous allons faire des cartes pour chaque situation à améliorer ;-)

**Comment by EmmanuelDemey** [comment]
Je vais passer cette carte à pret pour la prod (afin de faciliter notre nouveau wrkflow), tout en créant les tickets associés suite à tes remarques @Emilia-Vittek . Je ferai cela, surement après mes congés (donc à partir du 11/03).
