### ISSUE TITLE
utiliser un timbre ANONYME/INCONNU lorsque le jeton de l'utilisateur n'en contient pas

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Bauhaus-Back-Office#390]
L'information sur le timbre de l'utilisateur (contenu dans le jeton OIDC d'authent) est utilisée à plusieurs endroits dans Bauhaus (9 fois). Cette information est donc indispensable.

Lorsque l'utilisateur n'a pas de timbre (cas d'un stagiaire ?), je propose d'en affecter un par défaut : "INCONNU", "ANONYME", "bauhausGuest" (ne correspond avec aucun timbre officiel et donc ne donne aucun droit) pour que l'utilisateur puisse quand même naviguer dans Bauhaus en lecture.

**Comment by FBibonne** [comment]
#392

**Comment by FBibonne** [comment]
#391

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois et @FBibonne sera en charge de recette ce ticket.
