### ISSUE TITLE
La configuration du contrôle d'accès s'appuie sur WebSecurityConfigurerAdapter qui est déprécié

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Bauhaus-Back-Office#391]
Il faut revoir la configuration du contrôle d'accès pour supprimer WebSecurityConfigurerAdapter (cf. cet article 
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter ou encore https://spring.io/blog/2023/08/22/tackling-the-oauth2-client-component-model-in-spring-security)

**Comment by FBibonne** [comment]
Corriger également la typo : https://github.com/InseeFr/Bauhaus-Back-Office/blob/main/src/main/resources/bauhaus-dev.properties#L32

**Comment by FBibonne** [comment]
Corriger également message de la log :
```

	jar:file:/C:/INSEE/mavenrepository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
	jar:file:/C:/INSEE/mavenrepository/org/json/json/20230618/json-20230618.jar!/org/json/JSONObject.class
```

**Comment by FBibonne** [comment]
> Corriger également la typo : https://github.com/InseeFr/Bauhaus-Back-Office/blob/main/src/main/resources/bauhaus-dev.properties#L32

FAIT

**Comment by FBibonne** [comment]
> Corriger également message de la log :
> 
> ```
> Found multiple occurrences of org.json.JSONObject on the class path:
> 
> 	jar:file:/C:/INSEE/mavenrepository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
> 	jar:file:/C:/INSEE/mavenrepository/org/json/json/20230618/json-20230618.jar!/org/json/JSONObject.class
> ```

FAIT

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois et @FBibonne sera en charge de recette ce ticket.
