### ISSUE TITLE
ajout des timbres en dur

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Bauhaus-Back-Office#394]
En paliatif des problèmes d'interrogation de l'annuaire RH pour récupérer les timbres on va mettre en dur les timbres des unités insee, en plus des timbres SSM qui le sont déjà

**Comment by FBibonne** [comment]
Petite explication pour les développeurs : 
La branche d'annuaire requêtée par la méthode RmesStampsImpl.getStamps n'existe plus, ce qui fait échouer la méthode et le endpoint GET /stamps qui l'utilise ne fonctionne plus. Il faut remplacer l'appel à l'annuaire par la liste de codes dans le fichier ci-dessus pour rétablir le service (en attendant mieux).
Voir également si d'autres appels au même annuaire existent dans l'application et s'ils sont impactés par le problème

**Comment by EmmanuelDemey** [comment]
PR réalisé : https://github.com/InseeFr/Bauhaus-Back-Office/pull/395

**Comment by Emilia-Vittek** [comment]
@FBibonne  @JeromeMBourgeois @EmmanuelDemey Merci d'avoir avancé sur le sujet. :-) Il est d'autant plus important que, sauf erreur de ma part cela doit aussi "planter" en prod. Nous risquons de voir s'interroger un producteur qui aurait décidé de mettre à jour ses métadonnées ;-)
Plus nous passerons vite en prod et mieux cela sera, bien évidemment.
==> pour information, @flo7894 @ChristopheYon , _a minima._
