### ISSUE TITLE
Zones géographiques : zonages à façon en anglais

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#406]
_Description_
Dans le cadre des rapports qualité, lorsque le champs S.3.7 - Zone géographique de référence est créé à façon par le producteur :

- pouvoir saisir et stocker un libellé en langue 2 (en l'occurrence en anglais) ;
- rendre ce champ obligatoire également.

_Carte créée dans trello le 3 avril 2023_

**Comment by EmmanuelDemey** [comment]
2 PR: 

Back: https://github.com/InseeFr/Bauhaus-Back-Office/pull/407
Front: https://github.com/InseeFr/Bauhaus/pull/481

**Comment by flo7894** [comment]
en modification (bouton "voir"), les changements sur le libellé anglais ne sont pas pris en compte

**Comment by EmmanuelDemey** [comment]
@flo7894 une nouvelle PR a été créé : https://github.com/InseeFr/Bauhaus/pull/500

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/418

**Comment by EmmanuelDemey** [comment]
PR pour la prod 

https://github.com/InseeFr/Bauhaus/pull/529
https://github.com/InseeFr/Bauhaus-Back-Office/pull/465
