### ISSUE TITLE
paginer la page de visualisation d'une page liste de code

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#411]
Pour modéliser les fichiers de la base permanentes des équipements, j'ai chargé les listes de communes (CL_DEPCOM) et des iris (CL_DIRIS) sur dv1 le front et l'api magma freeze quand on essaye de récupérer ces listes.

**Comment by EmmanuelDemey** [comment]
@flo7894 même si je suis d'accord que ajouter une vraie pagination un peu partout dans l'application est nécessaire, j'ai peur que pour les codes Lists cela soit un peu compliqué. 
Car d'après ce que je vois , lorsque on récupère les codes actuels, nous devons faire des traitement sur l'ensemble des codes (ordonnancement, gestion des parents, gestion des SEQ). 
Donc si nous faisons une pagination, coté back, nous serions tout de même obligé de récupérer tous les codes, cela en perd de l'interet. Qu'en penses tu ?

**Comment by EmmanuelDemey** [comment]
- [ ] Supprimer le code pour l'ordonnancement des codes
- [ ] Gérer la pagination coté back
- [ ] Changer le front pour gérer le nouveau model de donnée
- [ ] Gérer la pagination coté front
- [ ] Modifier coté Back la création et mise à jour d'un code 
- [ ] Modifier coté front la page d'édition suite à la nouvelle structure de données

**Comment by EmmanuelDemey** [comment]
Je viens de finir le code coté Back. Je vais commencer à présent le front.

**Comment by flo7894** [comment]
@EmmanuelDemey 

il semble y avoir une regression sur le module opération suite à la pagination. le module utilise CL_FREQ et CL_SOURCE_CATEGORY et les réponses qu'il reçoit maintenant ne contiennent plus le libellé et l'identifiant de la liste et il lui manque les codes

**Comment by EmmanuelDemey** [comment]
Nouvelles PRS 
https://github.com/InseeFr/Bauhaus/pull/532
https://github.com/InseeFr/Bauhaus-Back-Office/pull/466/

**Comment by flo7894** [comment]
@EmmanuelDemey 
il semble y avoir un problème pour les listes très longues quand on atteint la page 51, on a une erreur 500 avec le message {"message":"Lexical error at line 48, column 18.  Encountered: '160' (160),"}

**Comment by EmmanuelDemey** [comment]
@flo7894 oh je regarde ça

**Comment by EmmanuelDemey** [comment]
@flo7894 je n'ai pas reussi à avoir exactement le même message d'erreur (line 48 et column 18), mais en tout cas j'ai reussi à avoir une Lexical Error. 

Je viens de faire une PR https://github.com/InseeFr/Bauhaus-Back-Office/pull/471/

**Comment by EmmanuelDemey** [comment]
Quand cette PR sera mergée sur main, il faudra vérifier sur le front
- la récupération des liste pour le module opération
- pour le module code list 
- poru le module dataset
