### ISSUE TITLE
Bauhaus QF : correctif pour éviter l'Erreur à la première connexion

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#415]

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek doit récupérer la description depuis Trello.

**Comment by Emilia-Vittek** [comment]
Nécessité de retourner chercher les certificats lors de la première connexion sur la QF (et de façon aléatoire de temps en temps, tous les un à deux ans). Est-ce toujours d'actualité ?

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois @FBibonne c'est pour vous je pense
