### ISSUE TITLE
Bug à l'édition d'une note de nomenclature

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#420]
Quand on modifie une note d'un poste de nomenclature par Bauhaus, l'enregistrement se fait bien dans le triplet evoc:noteLiteral est bien mis à jour mais pas le triplet xkos:plainText. 
Il faudrait mettre aussi à jour le triplet xkos:plainText (comme pour les concepts en transformant depuis le XHTML du noteLiteral)

**Comment by EmmanuelDemey** [comment]
@ChristopheYon je n'arrive pas à reproduire le problème. Quand je modifie, dans la nomenclature ci-dessous, une ChangeNote et une ScopeNote, la donnée est bien mise à jour à la fois en evo:noteLiteral et en xkos:plainText. 

Peux tu m'expliquer en détail ce que je dois faire pour réproduire. 



![Image](https://github.com/InseeFr/Bauhaus-Back-Office/assets/555768/98933565-f940-4d82-9c2a-cdcce68bc504)

**Comment by ChristopheYon** [comment]
@EmmanuelDemey 
Le problème est au niveau des notes des postes de la nomenclature, pas des notes de la nomenclature elle-même : dans l'écran de ton image, suis le dernier lien tout en bas "CPF rév 2.1, 2015 - Niveau 6 - Sous-catégories" puis va dans la page de n'importe quel poste du niveau (par exemple le premier "01.11.11 - Blé dur", qui correspond à l'url /classifications/classification/cpfr21/item/01.11.11 dans l'application). 
Là, si tu modifies le texte du "contenu central" (actuellement "froment dur") et tu sauvegardes : la modification est bien sauvegardée dans le evoc:noteLiteral mais pas dans le xkos:plainText.

**Comment by EmmanuelDemey** [comment]
Merci @ChristopheYon . Je vais tester ça alors.

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/435

**Comment by EmmanuelDemey** [comment]
PR pour la prod https://github.com/InseeFr/Bauhaus-Back-Office/pull/447
