### ISSUE TITLE
Problème Code List Partielle avec un identifiant ayant au moins un espace

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#430]

**Comment by EmmanuelDemey** [comment]
@flo7894 tu te souviens du problème ? Car je ne retrouve plus la PR réalisé, afin de pouvoir en faire une nouvelle vers la prod.

**Comment by flo7894** [comment]
@EmmanuelDemey oui comme l'identifiant sert à la construction de l'uri de l'objet il ne fallait pas permettre d'enregistrer une liste de code partielle avec un espace dans le champ identifiant (triplet <uriListe> skos:notation "identifiant")

**Comment by EmmanuelDemey** [comment]
PR pour la prod. https://github.com/InseeFr/Bauhaus/pull/510
