### ISSUE TITLE
Bug en prod à l'insertion d'un fichier

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#436]
Quand on insert un fichier dans un document et qu'on le sauvegarde on devrait créer un triplet \<uriDoc\> schema:url "chemin_applishare_fichier"

Ca se fait bien mais en plus on se retrouve avec des triplets
\<uriAutresDoc\> schema:url "chemin_applishare_fichier" pour d'autres documents

A priori le problème devrait venir d'un contrôle pas assez stricte sur la fin de l'uri du document si le document modifié est uriDoc = .../document/32 alors le fichier se retrouve également associée aux autres documents qui contiennent 32 (ex dans la base de test /232, /1032, /732 ...)

Également il semble qu'il n'y a pas de distinction entre les documents et les liens, si le document modifié est uriDoc = .../document/110 alors le fichier est se retrouve également associé au lien dont l'uri est .../page/110

**Comment by EmmanuelDemey** [comment]
@flo7894 tu détectes ce problème lors de la mise à jour d'un document existant ? Ou même lors de la création ?

**Comment by flo7894** [comment]
@EmmanuelDemey je n'ai pas réussi à reproduire le problème au moment de la création

**Comment by EmmanuelDemey** [comment]
J'ai trouvé d'où venait le problème. De l'utilisation d'un STREND dans la requête sparlq.
