### ISSUE TITLE
Réparer les méthodes codebook si c'est pas cher, sinon ne rien faire.

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#454]

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois c'est cher ou pas 💰 ?

**Comment by dzkwsk** [comment]
un exemple de DDI 3_2, si la remise du service est ok, faudra tester avec une studyUnit en 3_3

[TIC22EXPORTDDI.20220928.zip](https://github.com/InseeFr/Bauhaus-Back-Office/files/14066142/TIC22EXPORTDDI.20220928.zip)

**Comment by EmmanuelDemey** [comment]
En attente de la mise en production de la version Spring Boot 3

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois il parait que @dzkwsk a une erreur 500.

**Comment by EmmanuelDemey** [comment]
@dzkwsk Jérome ne reproduit pas le problème. Quelle requete as tu réalisé ?

**Comment by GtanSndil** [comment]
Le service est bien OK
Spécifier dans le swagger le fait que le fichier en entrée doit être en UTF-8 sans bom
