### ISSUE TITLE
Ajouter les catalogues record

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#455]
L'introduction du catalogue record permet des distinguer entre la date de modification du jeu de données dans Bauhaus (c'est-à-dire qu'on modifie la description du jeu de données) et la modification des données.

**Comment by EmmanuelDemey** [comment]
@flo7894 doit spécifier cette carte.

**Comment by flo7894** [comment]
J'ai mis un exemple rdf et décrit les triplets dans https://github.com/orgs/InseeFr/projects/9/views/5?pane=issue&itemId=44964139

Par rapport à l'ihm existante ça se traduirait par le fait que les champs "propriétaire" et "gestionnaire" vont servir à alimenter les propriétés du dcat:CatalogRecord et plus celles du dcat:Dataset

Pour renseigner la date de modification des données, qui correspond à la propriété dcterms:created sur le dcat:Dataset on mettrait un champ date dans le formulaire de saisie (onglet informations générales)

**Comment by EmmanuelDemey** [comment]
Très clair @flo7894

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus/pull/528
https://github.com/InseeFr/Bauhaus-Back-Office/pull/461

**Comment by EmmanuelDemey** [comment]
Pour information, dans les PRs ci-dessus, j'ai aussi gérer le ticker #460 . Je vais donc clore ce ticket qui ne sert plus à rien.
