### ISSUE TITLE
ajouter service PATCH /dataset/{id}

### ISSUE THREAD

**Issue by HugoBouttes** [InseeFr/Bauhaus-Back-Office#473]
https://github.com/InseeFr/Magma/issues/128

**Comment by EmmanuelDemey** [comment]
```
PATCH /dataset/{id}
{
   numberOfObservation: 1
}
```

**Comment by EmmanuelDemey** [comment]
@flo7894 a 500.

**Comment by EmmanuelDemey** [comment]
@flo7894 je viens de corriger. C'est la documentation Swagger qui n'était ps bonne. il faut passe le nombre "3" par exemple dans le body. 
Tu peux recette cette carte, mais de toute façon nous allons créer un PATCH plus généraliste. Je vais créer une nouvelle carte pour cela.

**Comment by EmmanuelDemey** [comment]
Je t'ai fait une PR @HugoBouttes https://github.com/InseeFr/Bauhaus-Back-Office/pull/536

**Comment by EmmanuelDemey** [comment]
Nouvelle carte créée : https://github.com/orgs/InseeFr/projects/9/views/8?pane=issue&itemId=55159928
