### ISSUE TITLE
Ajout d'un triplet à l'enregistrement d'un dataset

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#474]
Lors de l'enregistrement d'un dataset, on enregistre également un catalogRecord, il manque sur cette ressource le triplet indiquant son type :

\<uriCatalogRecord> rdf:type dcat:CatalogRecord .

**Comment by EmmanuelDemey** [comment]
PR : https://github.com/InseeFr/Bauhaus-Back-Office/pull/478
