### ISSUE TITLE
Définition des droits pour l'ouverture du module "Structures"

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#477]
- [ ] InseeFr/Bauhaus-Back-Office#487
- [ ] InseeFr/Bauhaus#575

L'utilisateur de "structures et composants" a les droits suivants : 
    • consulter une structure ;
    • consulter un composant ;
    • faire une recherche avancée de structure ;
    • faire une recherche avancée de composant.

Le gestionnaire de "structures et composants" est un utilisateur dont le timbre fait partie des timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet). Il a les droits suivants : 
    • les droits de l'utilisateur de "structures et composants"  ;
et les droits spécifiques :   
    • créer une structure ;
    • créer un composant ;
    • dupliquer une structure ;
    • modifier une structure ;
    • modifier un composant ;
    • supprimer une structure, si elle est provisoire, jamais publiée ;
    • supprimer un composant, s’il est provisoire, jamais publié ;
    • publier une structure ;
    • publier un composant.

L'administrateurde "structures et composants" a les droits suivants : 
    • les droits de l'utilisateur de "structures et composants"  ;
    • les droits du gestionnaire de "structures et composants", quels que soient les timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet) ;
et les droits spécifiques :   
    • supprimer une structure, quel que soit son état ;
    • supprimer un composant, quel que soit son état.

En principe le rôle de l'utilisateur "structures et composants" et celui de l'administrateur "structures et composants" sont déjà spécifiés et mis en place (à vérifier).
Il reste à définir et mettre en place le rôle du gestionnaire "structures et composants".

**Comment by EmmanuelDemey** [comment]
j'ai vu qu'il y avait plusieurs nouveaux groupes dans l'annuaire, a priori pour gérer les droits sur structures. En fait on ne veut qu'un seul nouveau groupe, celui de gestionnaire de structures. Les droits d'admin sont à affecter au groupe Administrateur_RMESGNCS existant, et les droits utilisateurs correspondent à quelqu'un qui se connecte sur bauhaus mais n'est ni dans le groupe Administrateur_RMESGNCS, ni dans le groupe Gestionnaire_ structures_RMESGNCS

**Comment by GuyleneTandeauDeMarsac** [comment]
Confirmez-vous que quand on parle de l'utilisateur, on parle de tout utilisateur anonyme ?

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/481/files
