### ISSUE TITLE
Tester les req sparql ?

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#480]
Voir https://github.com/openlink/virtuoso-opensource/issues/846#issuecomment-503952166 ou creuser avec d'autres recherches web pour créer une base rdf in memory pour tester les req sparql lors des tests d'intégration

Il faut également créer un jeu de test complet mais pas trop volumineux

**Comment by EmmanuelDemey** [comment]
@FBibonne j'ai réfléchi ce weekend sur ce sujet. nous sommes d'accord que à l'heure actuelle, il est impossible de créer une base in memory de GraphDB. 

Proposition: 

Pourquoi utiliser testcontainer sur la CI. (on peut le détecter que nous sommes sur CI car Github Action valoriser une variable d'environnement de mémoire). 

Et en local, utilisez l'une de nos bases actuelles ? Il suffirait de s'assurait de dynamiquement créer un repository fictif avant les tests et le supprimer à la fin. 

Qu'en penses tu ?

**Comment by FBibonne** [comment]
Oui je pense qu'il faut utiliser testcontainer. Sur la CI et la plupart des workstation de dev, ça fonctionnera. A l'Insee, j'espère qu'on aura une solution viable avant la fin de l'année (avec l'arrivée du dev ops et de stack de plus en plus complexe, la situation actuelle avec podman devient difficilement soutenable). 
En attendant, il faudrait dire à testcontainer de ne pas ... démarrer de container sur nos postes mais de taper une base dédiée où les jeux de tests sont chargés puis de la recharger... A moins que testcontainer puisse démarrer des pod dans un environnement kubernetes ?
Il faut que je prenne le temps de regarder testcontainer

**Comment by FBibonne** [comment]
@FBibonne : regarder si test container est paramétrable
