### ISSUE TITLE
Définition des droits pour l'ouverture du module "Jeux de données"

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#482]
- [ ] InseeFr/Bauhaus#577

L'utilisateur de "jeux de données" a les droits suivants :
- [x] consulter un jeu de données ;
- [ ] consulter une distribution.

Le gestionnaire de "jeux de données" est un utilisateur dont le timbre fait partie des timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet). Il a les droits suivants :
• les droits de l'utilisateur de "jeux de données" ;
et les droits spécifiques :
- [x] créer un jeu de données ;
- [ ] créer une distribution ;
- [x] modifier un jeu de données ;
- [ ] modifier une distribution ;
- [x] supprimer un jeu de données, s’il est  provisoire, jamais publié ;
- [ ] supprimer une distribution, si elle est provisoire, jamais publiée ;
- [x] publier un jeu de données ;
- [ ] publier une distribution.

L'administrateur de "jeux de données" a les droits suivants :
• les droits de l'utilisateur de "jeux de données" ;
• les droits du gestionnaire de "jeux de données", quels que soient les timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet) ;
et les droits spécifiques :
- [ ] supprimer un jeu de données, quel que soit son état ;
- [ ] supprimer une distribution, quel que soit son état.

En principe le rôle de l'utilisateur "jeux de données" et celui de l'administrateur "jeux de données" sont déjà spécifiés et mis en place (à vérifier).
Il reste à définir et mettre en place le rôle du gestionnaire "jeux de données".

**Comment by flo7894** [comment]
@EmmanuelDemey 

oui suppression et publication ne sont pas encore implémentées
pour les distributions oui le contributor est le même que le dataset. 
idéalement il faudrait filtrer la liste des datasets dans le formulaire de création d'une distribution sur cette propriété contributor

**Comment by EmmanuelDemey** [comment]
Donc ne retourner que les datasets dont catalogRecord'm.conteibutor est égale au timbre de l'utilisateur connecté ?@flo7894

**Comment by flo7894** [comment]
@EmmanuelDemey oui dans le cas où il a le rôle gestionnaire

**Comment by EmmanuelDemey** [comment]
@flo7894 afin de ne rien oublier, je viens de créer 4 issues correspondant aux 4 actions manquantes sur le module dataset

**Comment by EmmanuelDemey** [comment]
@flo7894 @Emilia-Vittek Une petite question. D'après cette carte, tout le monde peut créer des dataset. C'est voulu ? 

En effet, à la création d'un nouveau dataset, nous ne connaissons pas encore le contributor que nous allons lui mettre. Donc nous pouvons pas vérifier le controle à ce niveau la ? 

Nous n'avons pas le problème pour les distributions, car nous allons filtrer sur les datasets donc le contributor est égal aux stamps de l'utilsateur. Il y aura donc un filtre.

**Comment by EmmanuelDemey** [comment]
De plus, à l'heure actuelle une distribution ne possède pas de validationState. Faut il l'ajouter ?

**Comment by flo7894** [comment]
@EmmanuelDemey 

Les gestionnaires et les administrateurs peuvent créer des jeux de données. A la création d'un jeu de données est-ce qu'on peut affecter par défaut à le timbre de l'utilisateur connecté au champ gestionnaire (mais lui laisser la possibilité de le modifier, notamment pour gérer le multigestionnaire).

Sur les distributions, a priori pas de validationState pour le moment, elles pourraient être publiées en même temps que le jeu de données. Ajouter une distribution implique de modifier la description du jeu de données.

**Comment by EmmanuelDemey** [comment]
@flo7894 donc si nous sommes gestionnaire, nous ne pouvons supprimer une distribution si et seulement si la dataset parent est Unpublished ?

**Comment by EmmanuelDemey** [comment]
J'ai eu @flo7894 hier. Pour historiser la reponse, oui on se base sur le statut de diffusion du dataset.
