### ISSUE TITLE
Définition des droits pour l'ouverture du module "Listes de codes"

### ISSUE THREAD

**Issue by GtanSndil** [InseeFr/Bauhaus-Back-Office#485]
- [ ] InseeFr/Bauhaus-Back-Office#491
- [ ] InseeFr/Bauhaus#576
- [x] #497

L'utilisateur de "liste de codes" a les droits suivants :
    • consulter une liste de codes ;
    • faire une recherche avancée de liste de codes.
Remarque : l'utilisateur de "listes de codes partielles" est défini avec les mêmes droits de consultation et de recherche avancée sur les listes de codes partielles.

Le gestionnaire de "listes de codes" est un utilisateur dont le timbre fait partie des timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet). Il a les droits suivants :
    • les droits de l'utilisateur de "listes de codes"  ;
et les droits spécifiques :
    • créer une liste de codes ;
    • modifier une liste de codes ;
    • supprimer une liste de codes, si elle est provisoire, jamais publiée ;
    • publier une liste de codes.
Remarque : le gestionnaire de "listes de codes partielles" sera défini ultérieurement.
 
L'administrateur de "listes de codes" a les droits suivants :
    • les droits de l'utilisateur de "listes de codes"  ;
    • les droits du gestionnaire de "listes de codes", quels que soient les timbres figurant dans la propriété dc:contributor de l’objet modifié (liste des timbres des gestionnaires de l’objet)  ;
et les droits spécifiques :
    • supprimer une liste de codes, quel que soit son état.
Remarque : l'administrateur de "listes de codes partielles" est défini avec la même fonctionnalité de suppression des listes de codes partielles.

En principe le rôle de l'utilisateur "listes de codes" et celui de l'administrateur "listes de codes" sont déjà spécifiés et mis en place (à vérifier).
Il reste à définir et mettre en place le rôle du gestionnaire "listes de codes".
Selon le même principe, le rôle de l'utilisateur "listes de codes partielles" et celui de l'administrateur "listes de codes partielles" sont déjà spécifiés et mis en place (à vérifier).

**Comment by EmmanuelDemey** [comment]
Nouvelle PR @PierreVasseur https://github.com/InseeFr/Bauhaus/pull/676
