### ISSUE TITLE
Etre capable de supprimer un Jeu de Données

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#493]
- [ ] Etre capable de faire supprimer un jeu de données coté Back
- [ ] Etre capable de faire supprimer un jeu de données coté Front

Pour la gestion des droits de cette action, il faudra regarder l'issue #482

**Comment by flo7894** [comment]
Les jeux de données peuvent être supprimés s'ils sont à l'état "unpublished" par un administrateur ou un gestionnaire de jeux de données dont le timbre est dans la liste des timbres "contributor" du jeux de données.

**Comment by flo7894** [comment]
En plus de supprimer les triplets dont le sujet est l'uri du jeu de données, il faudrait également supprimer les triplets liés à l'entrée de catalogue, la période temporelle couverte et l'identifiant alternatif.
