### ISSUE TITLE
Etre capable de supprimer une Distribution

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#495]
- [ ] Etre capable de faire supprimer une distribution coté Back
- [ ] Etre capable de faire supprimer une distribution coté Front

Pour la gestion des droits de cette action, il faudra regarder l'issue #482

**Comment by flo7894** [comment]
Les distributions peuvent être supprimées si elles sont à l'état "unpublished" par un administrateur ou un gestionnaire de jeux de données dont le timbre est dans la liste des timbres "contributor" de la distributions.

**Comment by flo7894** [comment]
le triplet <uriJeuxDeDonnees> dcat:distribution <uriDistribution> devrait également être supprimé
