### ISSUE TITLE
Modifier l'enregistrement en base pour les datasets

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#557]
Pour un jeu de données on enregistre en base les triplets suivants avec un litteral
\<uriDataset> dct:creator "Insee"
\<uriDataset> dct:publisher "Insee"
\<uriDataset> insee:archiveUnit "UA1"

Il faudrait à la place enregistrer une uri
\<uriDataset> dct:creator \<http://bauhaus/organisations/Insee>
\<uriDataset> dct:publisher \<http://bauhaus/organisations/Insee>
\<uriDataset> insee:archiveUnit \<http://bauhaus/identifierSchemes/uniteArchivageNamingScheme/identifier/UA1>

**Comment by EmmanuelDemey** [comment]
@flo7894  ce problème sera résolu via ces deux PR : 
https://github.com/InseeFr/Bauhaus-Back-Office/pull/558
https://github.com/InseeFr/Bauhaus/pull/720
