### ISSUE TITLE
PATCH Distribution

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#575]

**Comment by GuyleneTandeauDeMarsac** [comment]
@flo7894 
peux-tu préciser quels sont les champs qu'on voudrait pouvoir modifier lors du PATCH distribution ?

**Comment by GuyleneTandeauDeMarsac** [comment]
@flo7894 
quand on fait un PATCH de dataset, si son statut de validation était initialement à VALIDATED, alors on le passe à MODIFIED.
Question : si on modifie une distribution dont le dataset a son statut de validation à VALIDATED, doit-on passer ce dernier à MODIFIED ?
