### ISSUE TITLE
Ajouter un identifiant alternatif sur les jeux de données

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#582]

**Comment by flo7894** [comment]
@EmmanuelDemey  l'uri dans le graphe adms n'est pas la bonne on a \<http://bauhaus/identifiantsAlternatifs/catalogues/jeuDeDonnees/jd1006> au lieu de \<http://bauhaus/identifiantsAlternatifs/jeuDeDonnees/jd1006>

**Comment by EmmanuelDemey** [comment]
@flo7894 un fix vient d'etre poussé. En Revue pour le moment.
