### ISSUE TITLE
Filtrer le tableau des modalités d'une liste de codes

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#586]

**Comment by flo7894** [comment]
@EmmanuelDemey la valeur du champ total n'est pas modifiée quand met des filtres, est-ce qu'il ne manque pas une information pour savoir combien de pages sont disponibles après filtrage ?

**Comment by EmmanuelDemey** [comment]
@flo7894 un fix vient d'etre proposé et se trouve en revue de code pour le moment.
