### ISSUE TITLE
Vérifier que le skos:altLabel du module Nomenclature est retourné dans l'api principal GET (pour recherche)

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#602]

**Comment by flo7894** [comment]
@EmmanuelDemey dans les requêtes sparql modifiées pour prendre en compte les altLabel, il faudrait prendre aussi en compte la langue du altLabel et le fait qu'il peut y avoir plusieurs altLabel dans une même langue contrairement au prefLabel qui est unique pour une langue donnée.

**Comment by EmmanuelDemey** [comment]
@flo7894 je viens de refaire une PR en faisant un GROUP_CONCAT dans la requête Sparql.

**Comment by flo7894** [comment]
@EmmanuelDemey, il faudrait apporter le même correctif au niveau des séries de nomenclatures. 

Et en regardant la requête en question [src/main/resources/request/classifications/series/getSeries.ftlh](https://github.com/InseeFr/Bauhaus-Back-Office/pull/609/files#diff-76c6a1e146dab8bad4a478cb99e07f06da5221b055788ad3303ca70e8246b35c) , il y a aussi un problème dans le optional avec ?families au lieu de ?series

**Comment by EmmanuelDemey** [comment]
@flo7894 je viens de faire la PR .
