### ISSUE TITLE
Vérifier que le code HTTP 403 n'est utilisé que pour les problèmes de droits (vérifier que cela n'est pas utilisé pour de la donnée incorrecte

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#603]

**Comment by GuyleneTandeauDeMarsac** [comment]
on renvoie une RmesUnauthorizedException au lieu d'une RmesBadRequestException ici : 
- ErrorCodes.CODE_LIST_AT_LEAST_ONE_CODE, "A code list should contain at least one code");
- ErrorCodes.CODE_LIST_UNICITY
- ErrorCodes.OPERATION_SERIES_EXISTING_PREF_LABEL_LG1
- ErrorCodes.OPERATION_SERIES_EXISTING_PREF_LABEL_LG2
- ErrorCodes.CODE_LIST_DELETE_ONLY_UNPUBLISHED
- ErrorCodes.CODE_LIST_DELETE_CODELIST_WITHOUT_PARTIAL
- ErrorCodes.CONCEPT_DELETION_SEVERAL_GRAPHS
- ErrorCodes.OPERATION_FAMILY_EXISTING_PREF_LABEL_LG1
- ErrorCodes.OPERATION_FAMILY_EXISTING_PREF_LABEL_LG2
- ErrorCodes.OPERATION_OPERATION_EXISTING_PREF_LABEL_LG1
- ErrorCodes.OPERATION_OPERATION_EXISTING_PREF_LABEL_LG2
- ErrorCodes.OPERATION_INDICATOR_EXISTING_PREF_LABEL_LG1
- ErrorCodes.OPERATION_INDICATOR_EXISTING_PREF_LABEL_LG2
- ErrorCodes.OPERATION_DOCUMENT_LINK_EXISTING_LABEL_LG1
- ErrorCodes.OPERATION_DOCUMENT_LINK_EXISTING_LABEL_LG2
- ErrorCodes.COMPONENT_UNICITY
- ErrorCodes.COMPONENT_PUBLICATION_EMPTY_CREATOR
- ErrorCodes.COMPONENT_PUBLICATION_EMPTY_STATUS
- ErrorCodes.COMPONENT_PUBLICATION_VALIDATED_CONCEPT
- ErrorCodes.COMPONENT_PUBLICATION_VALIDATED_CODESLIST
 - ErrorCodes.STRUCTURE_UNICITY
- ErrorCodes.COMPONENT_UNICITY
- ErrorCodes.OPERATION_VALIDATION_UNPUBLISHED_SERIES

On renvoie une RmesUnauthorizedException  au lieu d'une RmesNotFoundException  ici :
ErrorCodes.SERIES_UNKNOWN_FAMILY

Question sur :
- ErrorCodes.DOCUMENT_DELETION_LINKED
- ErrorCodes.OPERATION_VALIDATION_UNPUBLISHED_SERIES (This operation cannot be published before its series is published)
