### ISSUE TITLE
Remplacer l'identifiant pour un UUID dans Jeux de données

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#651]
Pour les jeux de données et les distributions, il faudrait maintenant utiliser un UUID en objet du prédicat identifier
Cela implique également un changement dans les Uris.

http://bauhaus/catalogues/jeuDeDonnees/1c2446be-5fe7-4727-a1f0-df7a61daec5f

Pour le système de génération des UUID, on prendra la version 4

**Comment by HugoSNDIL** [comment]
Est-ce que il doit y avoir un préfixe dans l'id (par exemple jd pour les datasets et d pour les distributions) ?

**Comment by flo7894** [comment]
@EmmanuelDemey 
La description de l'issue est erronée, pour les distributions on voulait juste introduire l'UUID.
L'URI devrait être de la forme
http://bauhaus/catalogues/distribution/1c2446be-5fe7-4727-a1f0-df7a61daec5f
