### ISSUE TITLE
Modification sur la réponse du post de document

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#734]
lorsque l'on essaye de créer un document, avec un libellé lg1, un libellé lg2 ou un nom de fichier identique à celui d'un document existant, l'API renvoie une erreur 400 mais pas d'indication quant à l'erreur. L'utilisateur reste sur formulaire de saisie de document sans indication quant au problème

**Comment by EmmanuelDemey** [comment]
Ce ticket a été corrigé récemment suite à un retour de @CatherineGoillot . Elle est encore en revue de code, donc pas encore déployée en QF.

**Comment by CatherineGoillot** [comment]
Test : OK
Vu avec les tests sur le ticket #909
