### ISSUE TITLE
Modifications potentielles sur le put de document

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#735]
- [x] lorsque l'on essaye de modifier un document, avec un libellé lg1, un libellé lg2 ou un nom de fichier identique à celui d'un document existant, l'API renvoie une erreur 400 mais pas d'indication quant à l'erreur. L'utilisateur reste sur formulaire de saisie de document sans indication quant au problème
- [x] la méthode ne semble pas tenir compte correctement du paramètre ID. Un appel avec le paramètre 1977 et un body { "labelLg1":"test libellé identique", "labelLg2":"test same label", "descriptionLg1":"", "descriptionLg2":"", "url":"file:///mnt/applishare3/rmes/dv2/data/storage/documents/test-controle-libelles.txt", "lang":"fr", "sims":[], "id":"1977", "updatedDate":"2024-08-30", "uri":"http://bauhaus/documents/document/1976" } va modifier le document 1976 au lieu du 1977

**Comment by EmmanuelDemey** [comment]
Comme indiqué dans la #734 , le premier point a récémment été corrigé (mais pas encore déployé).
