### ISSUE TITLE
[Bug] Exportation d'une collection en ODT (langue 2) et en ODS : il manque la liste des concepts et leur nom

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#754]
**Cette carte est créée le 4 juillet 2024,** lors de la reprise des différentes cartes sur les noms de fichier. Elle correspond à un problème découvert au détour d'une recette.

_Dans le module "Concepts", à l'onglet "Collections"_
1. Suite à la séquence de clics suivants pour exporter la collection au format odt:
- exporter ;
- sélectionner une collection ;
- **exporter la collection en ODT (2nde langue),**
le fichier qui résulte de l'exportation ne comporte ni la liste des concepts en page 1, ni le nom de chaque concept dans la reprise des définitions.

2. Suite à la séquence de clics suivants pour exporter la collection au format ods:
- exporter ;
- sélectionner une collection ;
- **exporter la collection en ODS,**
le fichier qui résulte de l'exportation ne comporte pas les libellés en langue 2.

**Comment by CatherineGoillot** [comment]
On a testé toutes les exportations et tout est OK
