### ISSUE TITLE
mettre à jour la version de Bauhaus sur SSP Cloud

### ISSUE THREAD

**Issue by GtanSndil** [InseeFr/Bauhaus-Back-Office#761]
https://gestion-metadonnees-api.demo.insee.io/bauhaus/swagger-ui/index.html => c'est la version 3.3.1 au lieu de 3.26.6

**Comment by GtanSndil** [comment]
à faire si possible avant la réunion métier avec les SSM le 30/09

**Comment by CatherineGoillot** [comment]
Fait le 03/10/2024
