### ISSUE TITLE
Gestion des caractères diacritiques dans l'exportation des rapports SIMS du fait de la mention "Rapport qualité" et du nom de la série

### ISSUE THREAD

**Issue by Emilia-Vittek** [InseeFr/Bauhaus-Back-Office#784]
**Carte commencée dans sa rédaction le mercredi 13 décembre 2023 et premier jet achevé le jeudi 14 décembre 2023, stockée dans la colonne "A spécifier".** Elle reprend une question qui est apparue lors de la recette de la carte "Gérer la longueur du nom du ZIP lors de l'export d'un SIMS#503](https://github.com/InseeFr/Bauhaus/issues/503)"

Cette carte ne sera basculée en "Prêt pour un prochain sprint" que lorsque la carte "Supprimer le caractère diacritique sur les noms de fichiers https://github.com/InseeFr/Bauhaus/pull/388" aura été recettée.

Je prends une opération et j'exporte le rapport Sims avec tous ses documents.
Dans l'exportation avec au moins un document, il reste des caractères diacritiques (en l'occurrence le signe ": " au moins ) : 
 - dans le nom du dossier ;
 - dans le nom du fichier du rapport
  car il est ajouté la chaîne de caractères "Rapport qualité : " devant le nom de l'opération pour constituer le nom du rapport qualité ou SIMS. De plus le nom du fichier qui va permettre de repérer l'opération ou l'indicateur  conserve aussi des caractères diacritiques (caractère "é" dans le test que j'ai fait), ce qui laisse supposer qu'il n'est pas passsé par la nouvelle moulinette destinée à supprimer les caractères diacritiques.

Le 11 octobre 2024, je considère que cela peut être traité.

**Comment by EmmanuelDemey** [comment]
Uniformiser les libellé sur les concepts / collection : ID + Label

**Comment by CatherineGoillot** [comment]
Test : KO

Dans le nom du fichier, j'ai une majuscule qui ne devrait pas apparaître (elle suit un ^dans le nom de l'opération).
Dans l'IHM, le rapport s'appelle : 
Rapport qualité : Enquête annuelle de recensement 2022 
et le fichier d'export : 
rapportQualitéEnque**T**eAnnuelleDeRecensement2022

Quand j'exporte un rapport avec des documents, j'ai un message d'erreur dans l'IHM et dans la console.
J'ai bien un zip avec le bon nom mais il ne contient pas les documents.
Est-ce dû à une mauvaise copie de la base de gestion des documents ?
![Image](https://github.com/user-attachments/assets/83983ec1-8269-40ef-9741-aaacbcd0a397)

**Comment by EmmanuelDemey** [comment]
Pour moi tu aurais du meme avoir "rapportQualiteEnqueteAnnuelleDeRecensement2022" sans le 2
