### ISSUE TITLE
Libellé erroné quand on exporte un rapport qualité sans les documents (libellé = identifiant)

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus-Back-Office#788]
A l'export d'un rapport, sans document, on récupére un fichier 11111.odt, ou 11111 est (je pense) l'identifiant du rapport. On sevrait avoir le libellé (meme nom que le ZIP quand on télécharge avec les documents).

**Comment by CatherineGoillot** [comment]
Tests : OK

Le libellé est bien celui du rapport (série, opération ou indicateur).
