### ISSUE TITLE
Erreur 403 à la création de structure, d'un composant ou jeu de données

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus-Back-Office#799]
Avec le rôle gestionnaire (de structures ou de jeux de donnée).
Depuis le formulaire de création d'une structure, d'un composant ou d'un jeu de données lorsqu'on sauvegarde après avoir rempli correctement les champs obligatoires on reçoit une erreur 403 de la part du back

**Comment by EmmanuelDemey** [comment]
Je viens de creuser ce sujet, et j'ai ajouté des tests pour vérifier le comportement. 

Pour le moment, lors de la création d'une structure et d'un composant, on vérifier pour un gestionnaire son timbre avec celui du champ contributor renseigné dans le formulaire . 

Est-ce que c'est le fonctionnement souhaité ? Perso je trouve cela étrange. 

Pour les Dataset, nous ne vérifions pas le timbre lors de la création. Par contre je n'ai pas d'erreur pour ce module. 

@CatherineGoillot @flo7894

**Comment by EmmanuelDemey** [comment]
Structure: 403 - tu as un timbre X et tu es gestionnaire, tu essaie de créer une structure avec le contributor à X => 403

**Comment by EmmanuelDemey** [comment]
@flo7894 peux tu m'envoyer le JSON envoyé ? et ton timbre ?

**Comment by flo7894** [comment]
Avec le timbre : {"stamp":"DG75-L201"}

création d'une structure :
{"identifiant":"TEST_CREATION_2024_11_29_N10","labelLg1":"Test création 2024-11-29 n°10","labelLg2":"Test création 2024-11-29 n°10","descriptionLg1":"","descriptionLg2":"","disseminationStatus":"http://id.insee.fr/codes/base/statutDiffusion/PublicGenerique","contributor":["DG75-L201"],"componentDefinitions":[],"isRequiredBy":""}

création d'un composant : 
{"contributor":["DG75-L201"],"labelLg1":"Test création 2024-11-29 n°10","labelLg2":"Test création 2024-11-29 n°10","identifiant":"TEST_CREATION_2024_11_29_N10","type":"http://purl.org/linked-data/cube#AttributeProperty"}

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/821
